import { HomeComponent } from "@/components";

export const metadata = {
  title: "Weather Nextjs | Project",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <div className="bg-gradient-to-br from-[#394f68] to-[#142647] min-h-screen flex flex-col items-center justify-center p-3">
      <HomeComponent />
    </div>
  );
}
